### ISSUE TITLE
Permissions on file robot.txt

### ISSUE THREAD

**Issue by nicolasriquelme62** [MathiasReker/filepermissions#1]
Hello, I congratulate you on the module, it greatly simplifies identifying privilege errors.

We identify an error the only file that does not modify is the robot.txt currently when executing its module it leaves it with 666 privileges and the correct thing is 644. 

was validated in Prestashop 1.6 and 1.7.x

**Comment by MathiasReker** [comment]
Hello

Sorry, I cannot reproduce the problem. I think your host does not allow you to execute the commands used in the module.
